// <auto-generated />
namespace WebBuilder2014.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class pagesection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pagesection));
        
        string IMigrationMetadata.Id
        {
            get { return "201410040204268_pagesection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
