// <auto-generated />
namespace WebBuilder2014.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class wbtemplate12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wbtemplate12));
        
        string IMigrationMetadata.Id
        {
            get { return "201410182252426_wbtemplate12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
